#!/bin/bash

# Prompt the user to enter the array elements
read -p "Enter the elements of the array separated by space: " -a array

# Get the length of the array
length=${#array[@]}

# Sort the array in descending order using a simple bubble sort
for ((i = 0; i < length; i++)); do
    for ((j = 0; j < length - i - 1; j++)); do
        if [ ${array[j]} -lt ${array[j+1]} ]; then
            # Swap elements
            temp=${array[j]}
            array[j]=${array[j+1]}
            array[j+1]=$temp
        fi
    done
done

# Display the sorted array
echo "Array in descending order: ${array[@]}"
